version: '3'

services:
  web:
    depends_on:
      - activemq
    build: .
    ports:
      - "8080:8080"
  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
